"""Photoshop JSX スクリプト生成.

PSD と同じフォルダに出力された .jsx を Photoshop で
「ファイル > スクリプト > 参照」から実行すると、
text_NN レイヤーの隣に編集可能なテキストレイヤー (TXT_NN) が追加される。
"""
from __future__ import annotations

import json
from pathlib import Path

from .ocr import TextRegion
from .utils import get_logger

logger = get_logger(__name__)


_JSX_TEMPLATE = r"""// Auto-generated by lp2psd. Run on the matching PSD.
// 各 text_NN レイヤーの bbox に、編集可能テキストレイヤー TXT_NN を追加する。
#target photoshop

(function () {
    if (app.documents.length === 0) {
        alert("先にPSDをPhotoshopで開いてからスクリプトを実行してください。");
        return;
    }
    var doc = app.activeDocument;
    var origUnits = app.preferences.rulerUnits;
    app.preferences.rulerUnits = Units.PIXELS;

    var regions = __REGIONS_JSON__;

    function addEditableText(idx, text, x, y, w, h, isVertical) {
        var layer = doc.artLayers.add();
        layer.kind = LayerKind.TEXT;
        layer.name = "TXT_" + idx;
        var t = layer.textItem;
        t.contents = text;
        if (isVertical) {
            try { t.direction = Direction.VERTICAL; } catch (e) {}
        }
        // フォントサイズは bbox の長辺 80% を初期推定値とする
        var sizePx = Math.max(8, Math.floor((isVertical ? w : h) * 0.8));
        t.size = new UnitValue(sizePx, "px");
        // 配置: テキストは baseline 基準なので、bbox の左下に揃える
        t.position = [new UnitValue(x, "px"), new UnitValue(y + h, "px")];
        // フォント色は黒を初期値（後で手動調整）
        var c = new SolidColor();
        c.rgb.red = 0; c.rgb.green = 0; c.rgb.blue = 0;
        t.color = c;
        return layer;
    }

    for (var i = 0; i < regions.length; i++) {
        var r = regions[i];
        try {
            addEditableText(r.idx, r.text, r.x, r.y, r.w, r.h, r.vertical);
        } catch (e) {
            $.writeln("Failed for region " + r.idx + ": " + e);
        }
    }

    app.preferences.rulerUnits = origUnits;
    alert("追加完了: " + regions.length + " 個の編集可能テキストレイヤー");
})();
"""


def write_jsx(regions: list[TextRegion], output_path: str | Path) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    payload = []
    for idx, r in enumerate(regions, start=1):
        payload.append(
            {
                "idx": f"{idx:02d}",
                "text": r.text,
                "x": int(r.bbox.x),
                "y": int(r.bbox.y),
                "w": int(r.bbox.w),
                "h": int(r.bbox.h),
                "vertical": bool(r.is_vertical),
            }
        )
    regions_json = json.dumps(payload, ensure_ascii=False, indent=2)
    script = _JSX_TEMPLATE.replace("__REGIONS_JSON__", regions_json)

    output_path.write_text(script, encoding="utf-8")
    logger.info("JSX saved: %s (%d regions)", output_path, len(regions))
    return output_path
